name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Set up Kubernetes access
      uses: azure/setup-kubectl@v1
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Forward port to Kubernetes pod (if necessary)
      run: |
        kubectl port-forward pod/plt-ims-ssnc-k8s-uat-stable-78fc84c595-4622m 4500:80 &
        # Add a small delay to ensure port-forwarding is up before tests run
        sleep 5

    - name: Run tests
      run: npm test

    - name: Clean up Kubernetes port-forward
      run: |
        # Clean up the background process of port forwarding after tests
        kill $(lsof -t -i:4500)
